version: "3"
services:
  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./infra/nginx/logs:/etc/nginx/logs
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  app:
    build: ./infra/php
    volumes:
      - ./backend:/work

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 33060:3306

  front_app:
    build:
      context: .
      dockerfile: ./infra/node/Dockerfile
      args:
        - TZ=${TZ}
    volumes:
      - ./nuxt:/var/www/nuxt
    ports:
      - ${FRONT_PORT}:3000
    links:
      - web
    depends_on:
      - web
    tty: true


volumes:
  db-store:
